import { Db } from "mongodb";
import { Exercise } from "../model/Exercise";
import { ExerciseBank } from "../model/ExerciseBank";

const EXERCISES_COLLECTION = "exercises";
const EXERCISE_BANKS_COLLECTION = "exerciseBanks";

export class ExerciseStore {

    private db: Db;

    constructor(db: Db) {
        this.db = db;
    }

    /**
     * Batch-inserts exercise documents into the collection.
     * Returns the ids of the inserted exercises in the same order.
     */
    async insertBatch(exercises: Exercise[]): Promise<string[]> {

        if (exercises.length === 0) return [];

        await this.db.collection(EXERCISES_COLLECTION).insertMany(exercises.map(e => e.toBSON()), { ordered: false });

        return exercises.map(e => e.id);
    }

    /**
     * Inserts an exercise bank document into the collection.
     * Returns the id of the inserted bank.
     */
    async insertBank(bank: ExerciseBank): Promise<string> {

        await this.db.collection(EXERCISE_BANKS_COLLECTION).insertOne(bank.toBSON());

        return bank.id;
    }

    /**
     * Finds the exercise bank for a given moduleId.
     * Returns null if no bank exists for that module.
     */
    async findBankByModuleId(moduleId: string): Promise<ExerciseBank | null> {

        const doc = await this.db.collection(EXERCISE_BANKS_COLLECTION).findOne({ moduleId });

        if (!doc) return null;

        return ExerciseBank.fromBSON(doc as any);
    }

    /**
     * Lists all exercises for a given moduleId.
     */
    async listByModuleId(moduleId: string): Promise<Exercise[]> {

        const docs = await this.db.collection(EXERCISES_COLLECTION).find({ moduleId }).toArray();

        return docs.map(doc => Exercise.fromBSON(doc as any));
    }

    /**
     * Finds a single exercise by its id.
     * Returns null if not found.
     */
    async findById(id: string): Promise<Exercise | null> {

        const doc = await this.db.collection(EXERCISES_COLLECTION).findOne({ id });

        if (!doc) return null;

        return Exercise.fromBSON(doc as any);
    }

    /**
     * Appends exercise ids to an existing bank.
     * Also increments totalGenerated by the number of new ids and sets generatedAt.
     */
    async appendExercisesToBank(moduleId: string, exerciseIds: string[], generatedAt: Date): Promise<void> {

        await this.db.collection(EXERCISE_BANKS_COLLECTION).updateOne(
            { moduleId },
            {
                $push: { exerciseIds: { $each: exerciseIds } } as any,
                $inc: { totalGenerated: exerciseIds.length },
                $set: { generatedAt },
            }
        );
    }
}
