import { Db } from "mongodb";
import { LevelTestBank } from "../model/LevelTestBank";

const LEVEL_TEST_BANKS_COLLECTION = "levelTestBanks";

export interface InsertOneResult {
    status: "created" | "duplicate_level";   // Outcome of the insert: created on success, duplicate_level if a bank already exists for the level.
    bank: LevelTestBank;                      // The inserted bank (created) or the pre-existing one (duplicate_level).
}

/**
 * Sole DB accessor for the levelTestBanks collection.
 * Supports finding a bank by CEFR level, inserting a new bank (one per level), and appending exercise ids.
 */
export class LevelTestBankStore {

    private db: Db;

    constructor(db: Db) {
        this.db = db;
    }

    /**
     * Finds the level test bank for a given CEFR level.
     *
     * @param {string} cefrLevel - The CEFR level (A1..C2).
     *
     * @returns {Promise<LevelTestBank | null>} The bank, or null if none exists for the level.
     */
    async findByCefrLevel(cefrLevel: string): Promise<LevelTestBank | null> {

        const doc = await this.db.collection(LEVEL_TEST_BANKS_COLLECTION).findOne({ cefrLevel });

        if (!doc) return null;

        return LevelTestBank.fromBSON(doc as any);
    }

    /**
     * Inserts a new level test bank.
     * Enforces one bank per CEFR level: rejects with duplicate_level if a bank already exists for the level.
     *
     * @param {LevelTestBank} bank - The bank to insert.
     *
     * @returns {Promise<InsertOneResult>} created with the new bank, or duplicate_level with the existing one.
     */
    async insertOne(bank: LevelTestBank): Promise<InsertOneResult> {

        const collection = this.db.collection(LEVEL_TEST_BANKS_COLLECTION);

        const existing = await collection.findOne({ cefrLevel: bank.cefrLevel });

        if (existing) return { status: "duplicate_level", bank: LevelTestBank.fromBSON(existing as any) };

        await collection.insertOne(bank.toBSON());

        return { status: "created", bank };
    }

    /**
     * Appends exercise ids to an existing bank, increments totalGenerated by the number of ids added and updates generatedAt.
     *
     * @param {string} cefrLevel - The CEFR level of the bank to append to.
     * @param {string[]} exerciseIds - The exercise ids to append.
     * @param {string} generatedAt - ISO timestamp to set as the new generatedAt.
     *
     * @returns {Promise<LevelTestBank | null>} The updated bank, or null if no bank exists for the level.
     */
    async appendExerciseIds(cefrLevel: string, exerciseIds: string[], generatedAt: string): Promise<LevelTestBank | null> {

        const update = { $push: { exerciseIds: { $each: exerciseIds } }, $inc: { totalGenerated: exerciseIds.length }, $set: { generatedAt } };

        const doc = await this.db.collection(LEVEL_TEST_BANKS_COLLECTION).findOneAndUpdate({ cefrLevel }, update as any, { returnDocument: "after" });

        if (!doc) return null;

        return LevelTestBank.fromBSON(doc as any);
    }
}
